server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monbudget
    username: monbudget
    password: monbudget123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: local
  auth-server-url: http://keycloak.localhost/auth
  ssl-required: none
  resource: monbudget-api
  credentials:
    secret: 409ff46a-c85a-453d-ad94-03160a4364b7
  use-resource-role-mappings: true
  bearer-only: true
